// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCu9xUKOt60q1meas_tNupzfjeiqFc7dvM',
    appId: '1:1095450230639:web:fa72a7f705080ac48cb29a',
    messagingSenderId: '1095450230639',
    projectId: 'sales-manager-da6c2',
    authDomain: 'sales-manager-da6c2.firebaseapp.com',
    storageBucket: 'sales-manager-da6c2.firebasestorage.app',
    measurementId: 'G-S17JQCN7HF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtS0ZDm0aJR5aONOdZY7ejPqAFkeS7jAo',
    appId: '1:1095450230639:android:d2191e67635bdc068cb29a',
    messagingSenderId: '1095450230639',
    projectId: 'sales-manager-da6c2',
    storageBucket: 'sales-manager-da6c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCScVUiqgx-Ae9d__6U9ASOh6CM5gK5Xfc',
    appId: '1:1095450230639:ios:305ab6cae7c65af48cb29a',
    messagingSenderId: '1095450230639',
    projectId: 'sales-manager-da6c2',
    storageBucket: 'sales-manager-da6c2.firebasestorage.app',
    androidClientId:
        '1095450230639-f0b54pn50ocp1rqjrajduddg9lvjpi8f.apps.googleusercontent.com',
    iosClientId:
        '1095450230639-jus0gq8rq9p3447h88auaurncnvci7ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCScVUiqgx-Ae9d__6U9ASOh6CM5gK5Xfc',
    appId: '1:1095450230639:ios:305ab6cae7c65af48cb29a',
    messagingSenderId: '1095450230639',
    projectId: 'sales-manager-da6c2',
    storageBucket: 'sales-manager-da6c2.firebasestorage.app',
    androidClientId:
        '1095450230639-f0b54pn50ocp1rqjrajduddg9lvjpi8f.apps.googleusercontent.com',
    iosClientId:
        '1095450230639-jus0gq8rq9p3447h88auaurncnvci7ug.apps.googleusercontent.com',
    iosBundleId: 'com.example.salesManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCu9xUKOt60q1meas_tNupzfjeiqFc7dvM',
    appId: '1:1095450230639:web:070fb850bf7fc3558cb29a',
    messagingSenderId: '1095450230639',
    projectId: 'sales-manager-da6c2',
    authDomain: 'sales-manager-da6c2.firebaseapp.com',
    storageBucket: 'sales-manager-da6c2.firebasestorage.app',
    measurementId: 'G-D9YF9L8V5P',
  );
}
