name: flutter-ci
on:
push:
branches: [ main, dev ]
pull_request:
branches: [ main, dev ]


jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v4
- uses: subosito/flutter-action@v2
with:
flutter-version: "3.24.0"
- run: flutter --version
- run: flutter pub get
- run: flutter analyze
- run: flutter test
- run: flutter build apk --release